name: Generate Podfile

on:
  workflow_dispatch:

jobs:
  generate-podfile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter (latest, master channel)
        uses: subosito/flutter-action@v2
        with:
          channel: master

      - name: Resolve dependencies (locked)
        run: flutter pub get

      - name: Generate Podfile (if missing)
        run: |
          cd ios
          if [ ! -f Podfile ]; then
            pod init
          else
            echo "Podfile already exists, skipping pod init."
          fi

      - name: Commit Podfile
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ios/Podfile
          git commit -m "Add generated Podfile" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
