name: Generate Podfile

on:
  workflow_dispatch:

jobs:
  generate-podfile:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x'

      - name: Generate Podfile
        run: |
          cd ios
          flutter pub get
          pod init

      - name: Commit Podfile
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ios/Podfile
          git commit -m "Add generated Podfile" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
